#GOAL for motor controller instructions (diff drive setup)

bool forward
bool reverse
bool clockwise
bool counter_clockwise
bool idle

#motor effort values are bewteen [0,100]
float32 left_motors_effort
float32 right_motors_effort
---
#RESULT
string result
---
#FEEDBACK
